version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - "8888:8000"
    volumes:
    - ./avaluaproy:/code
  # UD9.2.a
    depends_on:
    - db
  db:
    image: postgres:14
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"