# Generated by Django 4.2 on 2023-12-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_myuser_activo_alter_myuser_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
