# Generated by Django 4.2 on 2024-01-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_myuser_username'),
        ('usuarios', 'users_migracion_inicial'),
    ]

    operations = [
    ]
