# Generated by Django 4.2 on 2023-11-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='critevaluacion',
            unique_together={('resultado_aprendizaje', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='resaprendizaje',
            unique_together={('modulo', 'codigo')},
        ),
    ]
