# Generated by Django 4.2 on 2023-11-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_critevaluacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critevaluacion',
            options={'ordering': ['resultado_aprendizaje__codigo', 'codigo'], 'verbose_name': 'Criterio Evaluacion', 'verbose_name_plural': 'Criterios Evaluacion'},
        ),
        migrations.AlterModelOptions(
            name='resaprendizaje',
            options={'ordering': ['codigo'], 'verbose_name': 'Resultado Aprendizaje', 'verbose_name_plural': 'Resultados Aprendizaje'},
        ),
        migrations.AlterField(
            model_name='critevaluacion',
            name='codigo',
            field=models.CharField(max_length=4, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='critevaluacion',
            name='descripcion',
            field=models.TextField(verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='critevaluacion',
            name='minimo',
            field=models.BooleanField(verbose_name='minimo'),
        ),
        migrations.AlterField(
            model_name='critevaluacion',
            name='resultado_aprendizaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.resaprendizaje', verbose_name='codigo'),
        ),
    ]
