# Generated by Django 4.2 on 2024-01-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_critevaluacion_options_and_more'),
    ]

    operations = [
    ]
