# Generated by Django 4.2 on 2024-01-12 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240110_1534'),
        ('core', 'core_migracion_inicial'),
    ]

    operations = [
    ]
