# Generated by Django 4.2 on 2024-01-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_merge_0004_auto_20240110_1534_core_migracion_inicial'),
        ('programacion_didactica', 'prog_didactica_migracions_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=256)),
                ('direccion', models.CharField(max_length=256)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CriterioEvalUD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.critevaluacion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_didactica.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionUDCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_aula.alumno')),
                ('crit_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.critevaluacion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_didactica.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_aula.alumno')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_aula.alumno')),
                ('res_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.resaprendizaje')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_aula.alumno')),
                ('crit_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.critevaluacion')),
            ],
        ),
    ]
