# Generated by Django 4.2 on 2024-01-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_merge_0004_auto_20240110_1534_core_migracion_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Instrumento Evaluacion',
                'verbose_name_plural': 'Instrumentos Evaluacion',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PondRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('resultado_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.resaprendizaje')),
            ],
            options={
                'verbose_name': 'Ponderacion RA',
                'verbose_name_plural': 'Ponderaciones RA',
                'ordering': ['resultado_aprendizaje__codigo'],
            },
        ),
        migrations.CreateModel(
            name='PondCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('criterio_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.critevaluacion')),
            ],
            options={
                'verbose_name': 'Ponderacion Criterios',
                'verbose_name_plural': 'Ponderaciones Criterios',
                'ordering': ['criterio_evaluacion__codigo'],
            },
        ),
        migrations.CreateModel(
            name='PondCritUD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('criterio_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.critevaluacion')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_didactica.unidad')),
            ],
            options={
                'verbose_name': 'Ponderacion Criterio Unidad',
                'verbose_name_plural': 'Ponderaciones Criterio Unidad',
                'ordering': ['unidad__nombre', 'criterio_evaluacion__codigo'],
                'unique_together': {('criterio_evaluacion', 'unidad')},
            },
        ),
    ]
